M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu22.04.1} date Sun 06 Oct 2024 14:21:25 BST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-10-06T14:21:25+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X110.098Y-91.743
X110.098Y-97.523
M30
